### ISSUE TITLE
Pagination is not compatible with UUID primary keys 

### ISSUE THREAD

**Issue by djmaze** [zweitag/yaml_db#3]
When using PostgreSQL and having a UUID type column as a primary key, the pagination might produce inconsistent results during dumping. UUIDs are not incrementing, but the pagination sorts by "id". That means when new records are inserted while the table is being dumped, they might appear randomly in pages, so pages might overlap. This leads to missing or duplicate records in the output.

So concerning code is at https://github.com/zweitag/yaml_db/blob/master/lib/serialization_helper.rb#L181.

**Comment by postbud** [comment]
command: 
***RAILS_ENV=development bundle exec rake db:data:dump***
console:
NoMethodError: undefined method `[]=' for #<ActiveRecord::Result:0x00000008ab5d30>
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:108:in `block in unhash_records'
/var/lib/gems/1.9.1/gems/activerecord-4.1.6/lib/active_record/result.rb:55:in `block in each'
/var/lib/gems/1.9.1/gems/activerecord-4.1.6/lib/active_record/result.rb:55:in `each'
/var/lib/gems/1.9.1/gems/activerecord-4.1.6/lib/active_record/result.rb:55:in `each'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:107:in `each_with_index'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:107:in `unhash_records'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/yaml_db.rb:47:in `block in dump_table_records'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:187:in `block in each_table_page'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:183:in `each'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:183:in `each_table_page'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/yaml_db.rb:46:in `dump_table_records'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:168:in `dump_table'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:151:in `block in dump'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:149:in `each'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:149:in `dump'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/serialization_helper.rb:14:in `dump'
/home/geronimo/.gem/ruby/1.9.1/gems/yaml_db_with_schema_tables-0.2.4/lib/tasks/yaml_db_tasks.rake:21:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:data:dump
(See full trace by running task with --trace)

Maybe incompatible with Rails 4.1.6?
